apiVersion: apps/v1
kind: Deployment
metadata:
  name: server1-envoy-sidecar-deployment
  labels:
    app: server1-envoy-sidecar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server1-envoy-sidecar
  template:
    metadata:
      labels:
        app: server1-envoy-sidecar
    # The imp stuff
    spec:
      # Deployment has 2 containers!
      containers:
      - name: server1-envoy-sidecar
        image: kennethkreindler/envoy:100423-14-35-45
        imagePullPolicy: Never
        ports:
        - containerPort: 5199
          name: envoy-port
      - name: server1
        image: kennethkreindler/server1:100423-12-27-48
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: server1-envoy-sidecar-svc
spec:
  type: ClusterIP
  selector:
    app: server1-envoy-sidecar
  ports:
  # Service only exposes the Envoy container
  - name: server1-envoy-sidecar-svc-port
    protocol: TCP
    port: 5199
    targetPort: envoy-port